services:
  website:
    depends_on:
      - db
    container_name: website
    image: website:latest
    networks:
      - website_network
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
  db:
    env_file: ".env.local"
    container_name: website_db
    image: postgres:15
    networks:
      - website_network
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

networks:
  website_network:
